FROM ubuntu:latest
LABEL maintainer=w33tmaricich@gmail.com

RUN apt-get update

COPY . /usr/src/

WORKDIR /usr/src/installation
RUN ./docker-install.sh

WORKDIR /usr/src/src

CMD ["python", "run.py"]
